name: dti-gnn
channels:
  - conda-forge
  - bioconda
dependencies:
  # Core Python
  - python=3.10
  - pip
  
  # Scientific Computing (conda-forge)
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - networkx
  
  # Chemistry (conda-forge/bioconda)
  - rdkit
  - biopython
  
  # Jupyter
  - jupyterlab
  - ipywidgets
  
  # Utilities
  - tqdm
  - pyyaml
  - requests
  
  # Install everything else via pip (more reliable)
  - pip:
    # PyTorch with CUDA 12.1 (stable version with good PyG support)
    - torch==2.3.1
    - torchvision==0.18.1
    - torchaudio==2.3.1
    - --extra-index-url https://download.pytorch.org/whl/cu121
    
    # PyTorch Geometric and dependencies (matching PyTorch 2.3.1 + CUDA 12.1)
    - torch-geometric
    - torch-scatter
    - torch-sparse
    - torch-cluster
    - torch-spline-conv
    - --find-links https://data.pyg.org/whl/torch-2.3.0+cu121.html
    
    # Protein/Drug specific
    - fair-esm
    - prody
    - deepchem
    
    # ML utilities
    - transformers
    - datasets
    - accelerate
    - captum
    - shap
    
    # Additional utilities
    - plotly
    - h5py
    - wget
