name: dti-gnn
channels:
  - conda-forge
  - bioconda
dependencies:
  # Core Python
  - python=3.10
  - pip
  
  # Scientific Computing (conda-forge)
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - networkx
  
  # Chemistry (conda-forge/bioconda)
  - rdkit
  - biopython
  
  # Jupyter
  - jupyterlab
  - ipywidgets
  
  # Utilities
  - tqdm
  - pyyaml
  - requests
  
  # Install everything else via pip (more reliable)
  - pip:
    # PyTorch with CUDA 11.8
    - torch>=2.1.0
    - torchvision>=0.16.0
    - torchaudio>=2.1.0
    - --extra-index-url https://download.pytorch.org/whl/cu118
    
    # PyTorch Geometric and dependencies
    - torch-geometric
    - torch-scatter
    - torch-sparse
    - torch-cluster
    - torch-spline-conv
    
    # Protein/Drug specific
    - fair-esm
    - prody
    - deepchem
    
    # ML utilities
    - transformers
    - datasets
    - accelerate
    - captum
    - shap
    
    # Additional utilities
    - plotly
    - h5py
    - wget

