name: dti-gnn
channels:
  - conda-forge
  - pytorch
  - nvidia
  - bioconda
dependencies:
  - python=3.10
  - pip=24.0
  
  # Core Deep Learning (conda-forge/pytorch channels)
  - pytorch>=2.1.0
  - torchvision>=0.16.0
  - torchaudio>=2.1.0
  - pytorch-geometric>=2.4.0
  - pytorch-scatter>=2.1.0
  - pytorch-sparse>=0.6.18
  - pytorch-cluster>=1.6.3
  - pytorch-spline-conv>=1.2.2
  
  # Chemical Informatics (conda-forge/bioconda)
  - rdkit>=2023.3.1
  - deepchem>=2.7.2
  - openmm>=7.6
  
  # Biological Data Processing (bioconda/conda-forge)
  - biopython>=1.81
  - fair-esm>=2.0.0
  - prody>=2.4.1
  
  # Data Processing (conda-forge)
  - numpy>=1.23.0
  - pandas>=1.5.0
  - scikit-learn>=1.2.0
  - scipy>=1.10.0
  
  # Visualization (conda-forge)
  - matplotlib>=3.6.0
  - seaborn>=0.12.0
  - plotly>=5.14.0
  - networkx>=3.0
  
  # Utilities (conda-forge)
  - tqdm>=4.65.0
  - requests>=2.28.0
  - h5py>=3.8.0
  - pyyaml>=6.0
  - wget
  
  # Jupyter and Notebooks (conda-forge)
  - jupyter>=1.0.0
  - jupyterlab>=3.6.0
  - ipywidgets>=8.0.0
  - notebook>=7.0.0
  
  # Model Interpretation (conda-forge)
  - shap>=0.41.0
  - captum>=0.6.0
  
  # Additional ML utilities (conda-forge)
  - transformers>=4.30.0
  - datasets>=2.14.0
  - accelerate>=0.21.0

